payload:
  - +.ig.me
  - +.wa.me
  - +.igtv.com
  - +.fbcdn.net
  - +.igcdn.com
  - +.intagrm.com
  - +.whatsapp.tv
  - +.instagy.com
  - +.intgram.com
  - +.whatsapp.cc
  - +.igsonar.com
  - +.whatsapp.net
  - +.whatsapp.org
  - +.imtagram.com
  - +.whatsapp.com
  - +.instagor.com
  - +.intagram.com
  - +.instgram.com
  - +.whatsapp.biz
  - +.instagda.com
  - +.instagrm.com
  - +.instagify.com
  - +.instagram.com
  - +.imstagram.com
  - +.whatsapp.info
  - +.instastyle.tv
  - +.instagran.com
  - +.instagrem.com
  - +.carstagram.com
  - +.instagranm.com
  - +.instamgram.com
  - +.instangram.com
  - +.instagramm.com
  - +.instagtram.com
  - +.instagramq.com
  - +.instaadder.com
  - +.instagramn.com
  - +.kingstagram.com
  - +.instagramci.com
  - +.instagmania.com
  - +.oninstagram.com
  - +.bookstagram.com
  - +.instagainer.com
  - +.instagramcn.com
  - +.instafallow.com
  - +.instagramtr.com
  - +.instaplayer.net
  - +.instagramdi.com
  - +.whatsapp-plus.me
  - +.wwwinstagram.com
  - +.instachecker.com
  - +.chickstagram.com
  - +.cdninstagram.com
  - +.instagramium.com
  - +.instagramkusu.com
  - +.instagramtips.com
  - +.whatsappbrand.com
  - +.whatsapp-plus.net
  - +.instafollower.com
  - +.web-instagram.net
  - +.lnstagram-help.com
  - +.instagram-help.com
  - +.whatsapp-plus.info
  - +.instagramphoto.com
  - +.instagramlogin.com
  - +.instagram-press.net
  - +.onlineinstagram.com
  - +.instagram-brand.com
  - +.instagramhilesi.org
  - +.instagramsepeti.com
  - +.instanttelegram.com
  - +.instagram-press.com
  - +.instagramizlenme.com
  - +.online-instagram.com
  - +.theinstagramhack.com
  - +.instagramhilecim.com
  - +.instagramhashtags.net
  - +.instagrampartners.com
  - +.compute.amazonaws.com
  - +.instagramtakiphilesi.com
  - +.instagram-engineering.com
  - +.instagramtakipcisatinal.net
  - +.achat-followers-instagram.com
  - +.acheterfollowersinstagram.com
  - +.acheter-followers-instagram.com
  - +.acheterdesfollowersinstagram.com
