payload:
  - DOMAIN-SUFFIX,optimizationguide-pa.googleapis.com
  - DOMAIN-SUFFIX,safebrowsing.google.com
  - DOMAIN-SUFFIX,mtalk.google.com
  - DOMAIN-SUFFIX,mdp-appconf-ru.heytapdl.com
  - DOMAIN-SUFFIX,clients4.google.com
