allow-lan: true
mode: rule
log-level: silent
ipv6: false

keep-alive-interval: 15
keep-alive-idle: 15
disable-keep-alive: false

find-process-mode: strict

proxy-providers:

  zieng2@provider:
    type: http
    path: ./providers/zieng2@provider.yaml
    url: https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt
    interval: 14400

    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 604800
      timeout: 1200

    override:
      # udp: true
      ip-version: ipv4-prefer

    filter: VK
    exclude-type: ss|trojan

unified-delay: false
tcp-concurrent: true

profile:
  store-selected: true

sniffer:
  enable: true
  cache-algorithm: arc
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
    TLS:

proxy-groups:

  - name: Режим
    type: select
    proxies:
      - Авто (быстрый)
      - Ручной
    exclude-type: DIRECT
    url: https://www.gstatic.com/generate_204

  - name: Ручной
    type: select
    include-all: true
    exclude-type: DIRECT
    url: https://www.gstatic.com/generate_204

  - name: Авто (быстрый)
    type: url-test
    hidden: true
    include-all: true
    exclude-type: DIRECT
    url: https://www.gstatic.com/generate_204
    interval: 60
    lazy: false
    tolerance: 100
    timeout: 1200

rule-providers:
  block@other:
    type: http
    path: ./rulesets/block@other.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/other/block@other.yaml
    interval: 259200 # 72 часа
    behavior: classical
    format: yaml

  sds@processes:
    type: http
    path: ./rulesets/sds@processes.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/processes/sds@processes.yaml
    interval: 259200
    behavior: classical
    format: yaml

  sds@ipcidr:
    type: http
    path: ./rulesets/sds@ipcidr.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/ipcidr/sds@ipcidr.mrs
    interval: 259200
    behavior: ipcidr
    format: mrs
  
  sds@domains:
    type: http
    path: ./rulesets/sds@domains.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/domains/sds@domains.mrs
    interval: 259200
    behavior: domain
    format: mrs

rules:
  - RULE-SET,block@other,REJECT
  - RULE-SET,sds@processes,DIRECT
  - RULE-SET,sds@ipcidr,DIRECT
  - RULE-SET,sds@domains,DIRECT
  - MATCH,Режим