allow-lan: true
mode: rule
log-level: warning
ipv6: false

keep-alive-interval: 15
keep-alive-idle: 15
disable-keep-alive: false

find-process-mode: strict

proxy-providers:

  zieng2@provider:
    type: http
    path: ./providers/zieng2@provider.yaml
    url: https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt
    interval: 14400

    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 604800
      timeout: 2000

    override:
      udp: true
      ip-version: ipv4-prefer

    exclude-filter: Yandex|Majordomo|cloud.ru
    exclude-type: ss|trojan

redir-port: 7893
tproxy-port: 7894

unified-delay: false
tcp-concurrent: true

profile:
  store-selected: true

sniffer:
  enable: true
  cache-algorithm: arc
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
    TLS:

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - tls://77.88.8.8
  nameserver:
    - tls://77.88.8.8
  fallback:
    - tls://77.88.8.8
  proxy-server-nameserver:
    - tls://77.88.8.8
  direct-nameserver:
    - dhcp://system

proxy-groups:

  - name: Режим
    type: select
    proxies:
      - Авто
      - Ручной
    exclude-type: DIRECT
    url: https://www.gstatic.com/generate_204

  - name: Авто
    type: fallback
    proxies:
      - Быстрый 1
      - Быстрый 2
      - Быстрый 3
      - Быстрый 4
      - Быстрый 5
    url: https://www.gstatic.com/generate_204
    interval: 60
    lazy: false
    timeout: 1200
    max-failed-times: 2

  - name: Ручной
    type: select
    include-all: true
    exclude-type: DIRECT
    url: https://www.gstatic.com/generate_204

  - name: Быстрый 1
    type: url-test
    hidden: true
    include-all: true
    filter: "#([0-9]{2}|100)"
    exclude-type: DIRECT

  - name: Быстрый 2
    type: url-test
    hidden: true
    include-all: true
    filter: "#(1[0-9]{2}|200)"
    exclude-type: DIRECT

  - name: Быстрый 3
    type: url-test
    hidden: true
    include-all: true
    filter: "#(2[0-9]{2}|300)"
    exclude-type: DIRECT

  - name: Быстрый 4
    type: url-test
    hidden: true
    include-all: true
    filter: "#(3[0-9]{2}|400)"
    exclude-type: DIRECT

  - name: Быстрый 5
    type: url-test
    hidden: true
    include-all: true
    filter: "#(4[0-9]{2}|500)"
    exclude-type: DIRECT

rule-providers:
  block@other:
    type: http
    path: ./rulesets/block@other.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/other/block@other.yaml
    interval: 259200 # 72 часа
    behavior: classical
    format: yaml

  sds@processes:
    type: http
    path: ./rulesets/sds@processes.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/processes/sds@processes.yaml
    interval: 259200
    behavior: classical
    format: yaml

  sds@ipcidr:
    type: http
    path: ./rulesets/sds@ipcidr.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/ipcidr/sds@ipcidr.mrs
    interval: 259200
    behavior: ipcidr
    format: mrs
  
  sds@domains:
    type: http
    path: ./rulesets/sds@domains.yaml
    url: https://github.com/tobedeclared/mihomo/raw/main/rules/domains/sds@domains.mrs
    interval: 259200
    behavior: domain
    format: mrs

rules:
  - RULE-SET,block@other,REJECT
  - RULE-SET,sds@processes,DIRECT
  - RULE-SET,sds@ipcidr,DIRECT
  - RULE-SET,sds@domains,DIRECT
  - MATCH,Режим